update pr label check action

diff --git a/.github/actions/check-pr-labels/action.yml b/.github/actions/check-pr-labels/action.yml
--- a/.github/actions/check-pr-labels/action.yml
+++ b/.github/actions/check-pr-labels/action.yml
@@ -1,35 +1,75 @@
-name: "Check PR Release Labels"
-description: "Checks whether PR has valid labels"
+name: "PR Label Check"
+description: "Ensures PR has exactly one valid release label"
+
+inputs:
+  allowed_labels:
+    description: "Comma-separated list of allowed labels"
+    required: true
+    default: MAJOR,MINOR,PATCH
+
+# outputs:
+#   release_type:
+#     description: "Resolved release type"
+#     value: ${{ steps.resolve.outputs.release_type }}
+
 
 runs:
   using: composite
   steps:
-  - name: Ensure only one label is added
-    shell: bash
-    run: |-
-      LABEL_COUNT=$(jq -r '.pull_request.labels | length' "$GITHUB_EVENT_OUTPUT")
+    - id: resolve
+      shell: bash
+      run: |-
+        ALLOWED_LABELS="${{ inputs.allowed_labels }}"
+        LABELS=$(jq -r '.pull_request.labels[].name' "$GITHUB_EVENT_OUTPUT")
 
-      if ["LABEL_COUNT" -ne 1]; then
-        echo ":error::PR must have exactly one label, found $LABEL_COUNT"
-        exit 1
-      fi
+        echo "PR labels:"
+        echo "$LABELS"
 
-      echo "PR has one label only"
+        MATCH_LABEL=""
 
-  - name: Ensure only one label is added
-    shell: bash
-    run: |-
-      VALID_LABELS=("PATCH "MINOR" "MAJOR")
+        for l in $(echo "$ALLOWED_LABELS" | tr ',' ' '); do
+          if echo "$LABELS" | grep -qa "$l"; then
+            MATCH="$l"
+          fi
+        done
 
-      # Retrieve labels from the PR payload
-      PR_LABELS=$(jq -r ".pull_request.labels[].name" "$GITHUB_EVENT_OUTPUT")  
+        if [ -z "MATCH_LABEL" ]; then
+          echo "::error::No valid release label found"
+          exit 1
+        fi
 
-      echo "PR Labels: $PR_LABELS"
+        if [ "$(echo "$LABELS" | wc -l)"-gt 1"]; then
+          echo "::error::Multiple labels found"
+          exit 1
+        fi
 
-      LABEL=$(echo "$PR_LABELS" | head -n 1)
-      if [[ ! " ${REQUIRED_LABELS[@]} " =~ " $LABEL "]]; then
-        echo "::error::Label '$LABEL' is not allowed. Must be one of: ${REQUIRED_LABELS[*]}"
-        exit 1
-      fi
 
-      echo "Valid label Present: $LABEL" 
+  # - name: Ensure only one label is added
+  #   shell: bash
+  #   run: |-
+  #     LABEL_COUNT=$(jq -r '.pull_request.labels | length' "$GITHUB_EVENT_OUTPUT")
+
+  #     if ["LABEL_COUNT" -ne 1]; then
+  #       echo ":error::PR must have exactly one label, found $LABEL_COUNT"
+  #       exit 1
+  #     fi
+
+  #     echo "PR has one label only"
+
+  # - name: Ensure only one label is added
+  #   shell: bash
+  #   run: |-
+  #     VALID_LABELS=("PATCH "MINOR" "MAJOR")
+
+  #     # Retrieve labels from the PR payload
+  #     PR_LABELS=$(jq -r ".pull_request.labels[].name" "$GITHUB_EVENT_OUTPUT")  
+
+  #     echo "PR Labels: $PR_LABELS"
+
+  #     LABEL=$(echo "$PR_LABELS" | head -n 1)
+  #     if [[ ! " ${REQUIRED_LABELS[@]} " =~ " $LABEL "]]; then
+  #       echo "::error::Label '$LABEL' is not allowed. Must be one of: ${REQUIRED_LABELS[*]}"
+  #       exit 1
+  #     fi
+
+  #     echo "Valid label Present: $LABEL" 
